services:

  db:
    image: postgres
    restart: always
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: rotodraft
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data: